name: Census Bureau Salary Classification Pipeline Workflow

# Controls when the action will run.
on:
  [push, workflow_dispatch]

jobs:
  test_census_bureau_model:
    name: test_census_bureau_model
    runs-on: ubuntu-latest

    steps:
      - name: Clone source conde
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
          
      - name: Install python dependecies
        run: pip install -r starter/requirements.txt
      
      - name: Run unit tests for training code
        run: |
              cd starter/model_training
              python -m pytest test_model.py
              
      - name: Run flake8 on training code
        run: |
              cd starter/model_training
              flake8 . 
